theme: jekyll-theme-hacker

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: jihedamine

# Social icons
github_username: jihedamine
bitbucket_username:
stackoverflow_id: 338784
twitter_username:
google_plus_id:
linkedin_username: jihedamine
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
