name: Code is poetry
meta_description: "Code is poetry"

markdown: redcarpet
highlighter: pygments
paginate: 15
baseurl: /
permalink: /:title
domain_name: 'http://jihedamine.github.io'
google_analytics: 'UA-60516726-1'
disqus-shortname: jihedamine
# Details for the RSS feed generator
url:            'http://jihedamine.github.io'
author:         'Jihed Amine Maaref'